name: 11.19 Health Check

on:
  push:
    branches:
      - master
# 11.19
jobs:
  health_check:
    steps:
      - name: Check the deployed service URL
        uses: Jtalk/url-health-check-action@v2.2
        with: 
          url: https://heroic-pokedex.herokuapp.com/health