name: Deployment pipeline

on:
  push:
    branches:
      - master
      # note that your "main" branch might be called main instead of master
  pull_request: # tehtävä 11.13
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ', '), '#skip') }} # 11.16
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      # 11.7
      - name: build
        run: npm run build
      - name: test
        run: npm test
      # 11.9
      - name: e2e tests
        uses: cypress-io/github-action@v4
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      # 11.10 pusketaan herokuun
      - name: deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "heroic-pokedex" #Must be unique in Heroku
          heroku_email: "simo.riihimaki@unicus.com"
          healthcheck: "https://heroic-pokedex.herokuapp.com/health"
          checkstring: "ok!"
          rollbackonhealthcheckfailed: true 
      # 11.18
      - name: Success Job
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: success()
        with:
          severity: info
          details: Successfully deployed new Pokedex version!
          description: deployed to https://heroic-pokedex.herokuapp.com by ${{github.event.commits[0].author.username}}!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Failed Job
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: failure()
        with:
          severity: error
          username: EpäOnnistui
          details: Build Failed!
          description: ${{github.event.commits[0].url}} by ${{github.event.commits[0].author.username}} broke the build!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  tag_release: # 11.15
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ', '), '#skip')}} # 11.16
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      # 11.15
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true
          INITIAL_VERSION: 1.0.0
          VERBOSE: true